Import("env")
import Version

################################################################################
# Flags
################################################################################

if env["SCONS_STAGE"] == "flags" :
	env["EVEXIN_CONTROLLERS_FLAGS"] = {
			"LIBPATH": [Dir(".")],
			"LIBS": ["EveXinControllers"]
		}


################################################################################
# Build
################################################################################

if env["SCONS_STAGE"] == "build" :
	myenv = env.Clone()
	myenv.BuildVersion("BuildVersion.h", project = "swift")
	myenv.UseFlags(env["SWIFTEN_FLAGS"])
	myenv.UseFlags(env["SWIFTEN_DEP_FLAGS"])
	myenv.StaticLibrary("EveXinControllers", [
		"Character.cpp",
		"DataController.cpp",
		"DataStore.cpp",
		#"FileDataStore.cpp",
		"GeneralResult.cpp",
		"HTTPRequest.cpp",
		"MainController.cpp",
		"Skill.cpp",
		"SkillLevel.cpp",
		"SkillOrderedList.cpp",
		"SkillPlan.cpp",
		"SkillPlanList.cpp",
		"SkillTree.cpp",
		"SqliteDataStore.cpp",
	])

	env.Append(UNITTEST_SOURCES = [
		File("UnitTest/SkillPlanTest.cpp"),
	])
